import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {AiOutlineMenu} from 'react-icons/ai'
import { Button, Drawer } from 'antd';
import { useState } from 'react';
import {TbCurrencyNaira} from 'react-icons/tb'
import {MdOutlineAddShoppingCart} from 'react-icons/md'
import {AiOutlineDollarCircle} from 'react-icons/ai'
import {BsShop} from 'react-icons/bs'
import { useRouter } from 'next/router';
import { NormalLoader } from '../components/loader/NormalLoader';
import { useEffect } from 'react';
import { Column } from '@ant-design/plots';
import Chart from '../components/chart/Chart';


interface Props {

}

export const getServerSideProps: GetServerSideProps = async (context) => {
  
  const i = '222'
  

  return {
    props: {
      i
    }
  }
}


const Home: NextPage = () => {
  const [loading, setLoading] = useState(false)
  const [open, setOpen] = useState(false);

  const showDrawer = () => {
    setOpen(true);
  };

  const onClose = () => {
    setOpen(false);
  };

  if(loading){
    return <NormalLoader />
  }



  return (
    <div className='h-full'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='pt-16 lg:pl-96  text-sm  '>
        <div className='p-8'>
          <section className='grid  md:grid-cols-2 gap-4'>
            <div className='h-32 bg-white p-6 rounded-md flex justify-between flex-col'>
              <div className='flex justify-between'>
                <div className=''>
                  <p className='m-0 text-base font-medium'>Total Revenue</p>
                  <p className='m-0'>(Last 30 Days)</p>
                </div>
                <span className='m-0 w-14 h-14 bg-emerald-100 rounded-full flex items-center justify-center'>
                  <TbCurrencyNaira size={30} className='text-emerald-500'/>
                </span>
              </div>
              <span className='text-lg font-medium'>N0.00</span>
            </div>
            <div className='h-32 bg-white p-6 rounded-md flex justify-between flex-col'>
              <div className='flex justify-between'>
                <div className=''>
                  <p className='m-0 text-base font-medium'>Total Order</p>
                  <p className='m-0'>(Last 30 Days)</p>
                </div>
                <span className='m-0 w-14 h-14 bg-red-100 rounded-full flex items-center justify-center'>
                  <MdOutlineAddShoppingCart size={30} className='text-red-500' />
                </span>
              </div>
              <span className='text-lg font-medium'>0</span>
            </div>
            <div className='h-32 bg-white p-6 rounded-md flex justify-between flex-col'>
              <div className='flex justify-between'>
                <div className=''>
                  <p className='m-0 text-base font-medium'>Todays Revenue</p>
                  <p className='m-0'>(Last 30 Days)</p>
                </div>
                <span className='m-0 w-14 h-14 bg-amber-100 rounded-full flex items-center justify-center '>
                  <AiOutlineDollarCircle size={30} className='text-amber-500' />
                </span>
              </div>
              <span className='text-lg font-medium'>N0.00</span>
            </div>
            <div className='h-32 bg-white p-6 rounded-md flex justify-between flex-col'>
              <div className='flex justify-between'>
                <div className=''>
                  <p className='m-0 text-base font-medium'>Total Shops</p>
                  <p className='m-0'>(Last 30 Days)</p>
                </div>
                <span className='m-0 w-14 h-14 bg-cyan-100 rounded-full flex items-center justify-center'>
                  <BsShop size={30} className='text-cyan-500' />
                </span>
              </div>
              <span className='text-lg font-medium'>10</span>
            </div>
          </section>
          <section className='mt-12'>
            <div className='bg-white py-6 px-2 rounded-md'>
              <h1 className='mb-4'>Sales chart</h1>
            <Chart />
            </div>
          </section>
          <section className=' text-base text-gray-500 xl:grid grid-cols-2 xl:gap-4'>
            <div className='mt-12 bg-white rounded-md'>
              <h1 className='text-center text-lg font-semibold p-4 text-gray-800'>Recent Orders</h1>
              <div className='overflow-x-auto'>
                <table className='w-full'>
                  <thead className=''>
                    <tr className='bg-gray-50 text-gray-600  '>
                      <th className='min-w-[14rem] p-4'>Tracking Numder</th>
                      <th className='p-4'>Total</th>
                      <th className='min-w-[10rem] p-4'>Order Date</th>
                      <th className='p-4'>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className='text-center'>hrhrhrh</td>
                      <td className='text-center'>kokf</td>
                      <td className='text-center'>jjfr</td>
                      <td className='text-center'>jiridr</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
            <div className='mt-12 bg-white rounded-md'>
              <h1 className='text-center text-gray-800 text-lg font-semibold p-4'>Recent Widthdrawals</h1>
              <div className='overflow-x-auto'>
                <table className='w-full'>
                  <thead className=''>
                    <tr className='bg-gray-100 text-gray-600 '>
                      <th className='min-w-[12rem] text-left p-4'>Shop Name</th>
                      <th className='p-4'>Amount</th>
                      <th className='p-4'>Status</th>
                      <th className='p-4'>Created</th>
                      <th className='p-4'>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td className='text-center'></td>
                      <td className='text-center'>hrhrhrh</td>
                      <td className='text-center'>kokf</td>
                      <td className='text-center'>jjfr</td>
                      <td className='text-center'>jiridr</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </section>
          <section className='mt-12 bg-white rounded-md'>
            <h1 className='text-center text-lg font-semibold p-4 text-gray-800'>Popular Products</h1>
            <div className='overflow-x-auto'>
              <table className='w-full'>
                <thead className=''>
                  <tr className='bg-gray-100 text-gray-600 '>
                    <th className='p-4'>ID</th>
                    <th className='min-w-[12rem] text-left p-4 pl-0'>Name</th>
                    <th className='p-4'>Total</th>
                    <th className='p-4'>Order Date</th>
                    <th className='p-4'>Status</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td className='text-center'>3</td>
                    <td className=''>hrhrhrh</td>
                    <td className='text-center'>kokf</td>
                    <td className='text-center'>jjfr</td>
                    <td className='text-center'>jiridr</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </section>
        </div>
      </main>
    </div>
  )
}

export default Home
